import 'translation_keys.dart' as translation;

class En {
  Map<String, String> get messages => {
        translation.chooseLang: "Choose Language",
        translation.appName: "Bouddha Matrimony",
        translation.eng: "English",
        translation.mar: "Marathi",
        // Nav tabs
        translation.home: "Home",
        translation.memCard: "memCard",
        translation.contactUs: "Contact Us",
        //Splash Buttons
        translation.alreadyAMember: "alreadyAMember",
        translation.registerAsMember: "registerAsMember",
        // Login
        translation.login: "Login",
        translation.email: "Email",
        translation.password: "Password",
        translation.forgotPassword: "Forgot Password ?",
        translation.phoneNumber: "Phone Number",
        translation.dontHaveAcc: "Don't have an account ? ",
        translation.create: "Create",
        // Forgot Password
        translation.forgotPassDesc:
            "Enter your email associated with your account and we will send an email with instructions to reset your password !",
        translation.sendInst: "Send Instructions",
        //Register
        translation.signUp: "SIGN UP",
        translation.fullName: "fullName",
        translation.varVadhuName: "Enter Var/Vadhu Name",
        translation.gender: "Gender",
        translation.male: "Male",
        translation.female: "Female",
        translation.dob: "Date Of Birth",
        translation.maritalStatus: "Maritial Status",
        translation.location: "Location",
        translation.mobileNumber: "Mobile Number",
        translation.createPass: "Create Password",
        translation.createProfile: "Create Profile",
        translation.next: "Next",
        translation.submit: "Submit",
        translation.previous: "Previous",
        //Basic Details
        translation.setupProfile: "SETUP PROFILE",
        translation.updateProfile: "UPDATE PROFILE",
        translation.basicDetails: "Basic Details",
        translation.name: "Name",
        translation.height: "Height",
        translation.dateOfBirth: "Date Of Birth",
        translation.maritialStatus: "Maritial Status",
        translation.single: "Single",
        translation.neverMarried: "Never Married",
        translation.married: "Married",
        translation.divorced: "Divorced",
        translation.widowed: "Widowed",
        translation.widower: "Widower",
        translation.hobbies: "Hobbies",
        translation.weight: "Weight",
        translation.birthTime: "Birth Time",
        translation.noChilderen: "No. Of Children",
        translation.mothertounge: "Mother Tounge",
        translation.languages: "Languages",
        translation.birthPlace: "Birth Place",
        translation.profileCreated: "Profile Created By",
        translation.self: "Self",
        translation.parents: "Parents",
        translation.sister: "Sister",
        translation.brother: "Brother",
        translation.guardian: "Guardian",

        translation.allFieldsMandatory: "All Fields are mandatory",
        // Education Details
        // translation.educationDetails: "Basic Details",

        translation.education: "Education",
        translation.occupation: "Occupation",
        translation.employeeIn: "Employee In",
        translation.designation: "Designation",
        translation.annualIncome: "Annual Income",
        // Lifestyle
        translation.lifestyleDetails: "Lifestyle Details",

        translation.bodyType: "Body Type",
        translation.skinTone: "Skin Tone",
        translation.bloodGrp: "Blood Group",
        translation.eatingHabit: "Eating Habit",
        translation.drinkingHabit: "Drinking Habit",
        translation.smokingHabit: "Smoking Habit",
        translation.yes: "Yes",
        translation.no: "No",
        //Location
        translation.locationDetails: "Location Details",
        translation.country: "Country",
        translation.state: "State",
        translation.city: "City",
        translation.address: "Address",
        translation.timeToCall: "Time To Call",
        translation.residence: "Residence (NRI/Citizen)",
        translation.nri: "NRI",
        translation.citizen: "Citizen",
        //Family Type
        translation.familyDetails: "Family Details",
        translation.familyType: "Family Type",
        translation.joint: "Joint",
        translation.nuclear: "Nuclear",
        translation.fathersName: "Father's Name",
        translation.fathersOccupation: "Father's Occupation",
        translation.mothersName: "Mother's Name",
        translation.mothersOccupation: "Mother's Occupation",
        translation.noOfBrothers: "No. Of Brothers",
        translation.noOfMarriedBrothers: "No. Of Married Brothers",
        translation.noOfSisters: "No. Of Sisters",
        translation.noOfMarriedSisters: "No. Of Married Sisters",
        translation.abtMyFamily: "About My Family",
        //Upload ID Proof
        translation.uploadIDProof: "Upload ID Proof",
        translation.updateIDProof: "Update ID Proof",
        translation.pleaseProvideProofDesc:
            "Please provide us your ID Proof for Authentication",
        translation.uploadIdProofAadhar:
            "Upload ID Proof (Prefferably Aadhaar Card)",
        translation.uploadYourPhoto: "Upload your Photo for Profile",
        translation.upload: "Upload",
        translation.uploadProof: "Upload Proof",
        //Basic Prefrence
        translation.updatePartnerPref: "Update Partner Preference",
        translation.partnerPref: "Partner Preference",
        translation.basicPref: "Basic Preferenece",
        translation.lookingFor: "Looking For",
        translation.fromAge: "From Age",
        translation.toAge: "To Age",
        translation.fromHeight: "From Height",
        translation.toHeight: "To Height",
        translation.any: "Any",
        translation.genralExpectation: "General Expectations",
        //Location Preference
        translation.locationPref: "Location Preference",
        translation.educationOccup: "Education & Occupation",
        //Home
        translation.matches: "Matches",
        translation.profileVisitors: "Profile Visitors",
        translation.noVisitors: "No Visitors !",
        translation.noProfiles: "No Profile !",
        translation.noBlockedProfiles: "No Blocked Profile !",
        translation.noMatches: "No Matches !",
        translation.shortlist: "Shortlist",
        //Matches
        translation.profileId: "Profile ID",
        translation.ageNHeight: "Age & Height",
        translation.age: "Age",
        translation.religion: "Religion",
        translation.caste: "Caste",
        translation.sendInterest: "Send Interest",
        //Interests
        translation.interest: "Interests",
        translation.receivedInterest: "Received Interests",
        translation.pending: "Pending",
        translation.rejected: "Rejected",
        translation.accepted: "Accepted",
        translation.accept: "Accept",
        translation.reject: "Reject",
        translation.updating: "Updating ...",
        translation.interestSent: "Interest Sent !",
        translation.unblock: "Un Block",
        translation.whatsappError: "WhatsApp is not installed on the device",
        //Search
        translation.search: "Search",
        translation.profileEdit: "Profiel Edit",
        //Blocked Profile
        translation.blockedProfile: "Blocked Profile",
        //News & Updated
        translation.newsUpdates: "News Update",
        //About Us
        translation.aboutUs: "About Us",
        //Package
        translation.upgradeNow: "Upgrade Now",
        translation.packages: "Packages",
        translation.chatRequest: "Chat Requests",
        translation.contactViews: "Contact Views",
        translation.planDuration: "Plan duration",
        translation.choose: "Choose",
        //Profile Details
        translation.profileDetails: "Profile details",
        translation.loading: "Loading",
        translation.basic: "Basic",
        translation.religious: "Religious",
        translation.subcaste: "Subcaste",
        translation.gotra: "Gotra",
        translation.lifestyle: "Lifestyle",
        translation.family: "Family",
        translation.call: "Call",
        translation.errorInterest: "Error Updating Interest Status !",
        translation.successInterest: "Interest Status Updated !",
        translation.block: "Block",
        translation.errorBlock: "Error Blocking this Profile !",
        translation.successBlock: "Profile Added to Block List !",
        //Settings
        translation.settings: "Settings",
        translation.inviteFriend: "Invite Friend",
        translation.subscriptions: "Subscriptions",
        translation.rateTheApp: "Rate The App",
        translation.termsCondition: "Terms & Conditions",
        translation.privacyPolicy: "Privacy Policy",
        translation.logout: "Logout",
        translation.allRightsReserved: "All Rights Reserved",
        translation.website: "Website",

        //ERRORS
        translation.errorUpdating: "Error Occured while Updating Details !",
        translation.successUpdating: "Details Updated Successfully !!",
        translation.successSubmiting: "Details Submitted Successfully !!",
        translation.settingUpAcc: "Seting Up App ..\nAnd Going to Home Screen",
        translation.errorShortlist: "Error Shortlisting Profile !",
        translation.successShortlist: "Profile Shortlisted !",
      };
}
